
<<<<<<< HEAD
const disasterList = [
=======
const roastList = [
>>>>>>> 9cf93e32c51af5f529d1164b1db6b55037e720a4
    '#ecosystem',
    '#nature',
    '#environment',
    '#ecology',
    '#climatechange',
    '#biodiversity',
    '#ecofriendly',
    '#earth',
    '#wildlife',
    '#conservation',
    '#china',
    '#pakistan',
    '#haiti',
    '#india',
    '#indianocean',
    '#japan',
    '#bangladesh',
    '#mongolia',
    '#unitedstates',
    '#philippines',
    '#cuba',
    '#bahamas',
    '#bermuda',
    '#puertorico',
    '#guadeloupe',
    '#dominica',
    '#iran',
    '#turkmenistan',
    '#caymanislands',
    '#nepal',
    '#canada',
    '#turkey',
    '#romania',
    '#saudiarabia',
    '#argentina',
    '#russia',
    '#guatemala',
    '#mexico',
    '#lesserantilles',
    '#vietnam',
    '#indonesia',
    '#honduras',
    '#nicaragua',
    '#elsalvador',
    '#belize',
    '#algeria',
    '#yemen',
    '#colombia',
    '#cameroon',
    '#ecuador',
    '#thailand',
    '#mozambique',
    '#france',
    '#portugal',
    '#unitedkingdom',
    '#netherlands',
    '#germany',
    '#spain',
    '#sweden',
    '#italy',
    '#luxemburg',
    '#ireland',
    '#srilanka',
    '#somalia',
    '#myanmar',
    '#syria',
    '#azerbaijan',
    '#georgia',
    '#italy',
    '#venezuela',
    '#peru',
    '#tajikistan',
    '#norway',
    '#worldwide',
    '#europe',
    '#asia',
    '#pandemic',
    '#africa',
    '#epidemics',
    '#greece',
    '#chile',
    '#ocean',
    '#antarctica',
    '#australia',
    '#northamerica',
    '#southamerica'
];

module.exports = function () {
<<<<<<< HEAD
    return disasterList[Math.floor(Math.random() * disasterList.length)];
=======
    return roastList[Math.floor(Math.random() * roastList.length)];
>>>>>>> 9cf93e32c51af5f529d1164b1db6b55037e720a4
};